[package]
name = "gsusb"
description = "Host driver for the Geschwister Schneider USB/CAN protocol"
version = "0.1.0"
edition = "2024"
readme = "README.md"
license = "MPL-2.0"
repository = "https://github.com/umi-eng/canbus"
categories = ["network-programming"]

[dependencies]
embedded-can = "0.4"
futures = "0.3"
nusb = "0.2"
thiserror = "2.0"
zerocopy = { version = "0.8", features = ["derive"] }

[features]
default = ["tokio"]
tokio = ["nusb/tokio"]
smol = ["nusb/smol"]

[dev-dependencies]
tokio = { version = "1.51", features = ["full"] }
