[package]
name = "gsusb"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-can = "0.4"
futures = "0.3"
nusb = "0.2.3"
thiserror = "2.0.18"
zerocopy = { version = "0.8", features = ["derive"] }

[features]
default = ["tokio"]
tokio = ["nusb/tokio"]
smol = ["nusb/smol"]

[dev-dependencies]
tokio = { version = "1.51", features = ["full"] }
