[package]
name = "korlan"
description = "Korlan USB2CAN driver"
version = "0.1.0"
edition = "2024"
authors = ["Liam Kinne <liam@umi.engineering>"]
readme = "README.md"
repository = "https://github.com/umi-eng/canbus"
license = "MPL-2.0"

[dependencies]
embedded-can = "0.4"
thiserror = "2.0"
futures = "0.3"
zerocopy = { version = "0.8", features = ["derive"] }
nusb = { version = "0.2.3" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[features]
default = ["tokio"]
tokio = ["nusb/tokio"]
smol = ["nusb/smol"]
