name: CANSocket Crate

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        if: ${{ github.ref != 'refs/heads/main' }}
      - name: Run unit tests
        working-directory: ./cansocket
        run: cargo test --lib
